version: '3'
services:
  backend-api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app            # Монтируем локальную папку в контейнер
      - /app/node_modules          # Исключаем node_modules контейнера, чтобы избежать конфликтов
    ports:
      - "4000:4000"                # Пробрасываем порт для backend
    environment:
      - NODE_ENV=development       # Переменная окружения для dev
      - MONGO_URI=mongodb://mongo:27017/mydb  # Строка подключения к MongoDB
    command: npm run start:dev      # Команда для запуска сервера в режиме разработки
    depends_on:
      - mongo                       # Обеспечиваем, чтобы MongoDB запускалась раньше backend

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app            # Монтируем локальную папку для frontend
      - /app/node_modules
    ports:
      - "3000:3000"                # Пробрасываем порт для frontend
    environment:
      - NODE_ENV=development
    command: npm start             # Команда для запуска frontend в dev

  mongo:
    image: mongo:latest            # Используем официальный образ MongoDB
    container_name: mongo
    ports:
      - "27018:27017"              # Пробрасываем порт для MongoDB
    volumes:
      - mongo-data:/data/db        # Монтируем volume для хранения данных

volumes:
  mongo-data:                      # Используем named volume для данных MongoDB
